/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppMentorshipIndexRouteImport } from './routes/_app/mentorship/index'
import { Route as AppKnowYourAlumniIndexRouteImport } from './routes/_app/know-your-alumni/index'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppDirectoryIndexRouteImport } from './routes/_app/directory/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppJobsNewRouteImport } from './routes/_app/jobs/new'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'
import { Route as AppDirectoryUserIdRouteImport } from './routes/_app/directory/$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorshipIndexRoute = AppMentorshipIndexRouteImport.update({
  id: '/mentorship/',
  path: '/mentorship/',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowYourAlumniIndexRoute = AppKnowYourAlumniIndexRouteImport.update({
  id: '/know-your-alumni/',
  path: '/know-your-alumni/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryIndexRoute = AppDirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryUserIdRoute = AppDirectoryUserIdRouteImport.update({
  id: '/directory/$userId',
  path: '/directory/$userId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/members': typeof AdminMembersRoute
  '/directory/$userId': typeof AppDirectoryUserIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/directory/': typeof AppDirectoryIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/know-your-alumni/': typeof AppKnowYourAlumniIndexRoute
  '/mentorship/': typeof AppMentorshipIndexRoute
  '/profile/': typeof AppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/members': typeof AdminMembersRoute
  '/directory/$userId': typeof AppDirectoryUserIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/directory': typeof AppDirectoryIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/know-your-alumni': typeof AppKnowYourAlumniIndexRoute
  '/mentorship': typeof AppMentorshipIndexRoute
  '/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/members': typeof AdminMembersRoute
  '/_app/directory/$userId': typeof AppDirectoryUserIdRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/directory/': typeof AppDirectoryIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/know-your-alumni/': typeof AppKnowYourAlumniIndexRoute
  '/_app/mentorship/': typeof AppMentorshipIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/jobs'
    | '/admin/members'
    | '/directory/$userId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/dashboard/'
    | '/directory/'
    | '/events/'
    | '/jobs/'
    | '/know-your-alumni/'
    | '/mentorship/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/jobs'
    | '/admin/members'
    | '/directory/$userId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/dashboard'
    | '/directory'
    | '/events'
    | '/jobs'
    | '/know-your-alumni'
    | '/mentorship'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/admin/jobs'
    | '/admin/members'
    | '/_app/directory/$userId'
    | '/_app/jobs/$jobId'
    | '/_app/jobs/new'
    | '/_app/dashboard/'
    | '/_app/directory/'
    | '/_app/events/'
    | '/_app/jobs/'
    | '/_app/know-your-alumni/'
    | '/_app/mentorship/'
    | '/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentorship/': {
      id: '/_app/mentorship/'
      path: '/mentorship'
      fullPath: '/mentorship/'
      preLoaderRoute: typeof AppMentorshipIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/know-your-alumni/': {
      id: '/_app/know-your-alumni/'
      path: '/know-your-alumni'
      fullPath: '/know-your-alumni/'
      preLoaderRoute: typeof AppKnowYourAlumniIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory/': {
      id: '/_app/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof AppDirectoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory/$userId': {
      id: '/_app/directory/$userId'
      path: '/directory/$userId'
      fullPath: '/directory/$userId'
      preLoaderRoute: typeof AppDirectoryUserIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDirectoryUserIdRoute: typeof AppDirectoryUserIdRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDirectoryIndexRoute: typeof AppDirectoryIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppKnowYourAlumniIndexRoute: typeof AppKnowYourAlumniIndexRoute
  AppMentorshipIndexRoute: typeof AppMentorshipIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDirectoryUserIdRoute: AppDirectoryUserIdRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppJobsNewRoute: AppJobsNewRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDirectoryIndexRoute: AppDirectoryIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppKnowYourAlumniIndexRoute: AppKnowYourAlumniIndexRoute,
  AppMentorshipIndexRoute: AppMentorshipIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMembersRoute: typeof AdminMembersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJobsRoute: AdminJobsRoute,
  AdminMembersRoute: AdminMembersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
